#ARG BASE_IMAGE=kinoite-main
#FROM ghcr.io/ublue-os/${BASE_IMAGE}:latest
FROM quay.io/fedora-ostree-desktops/kinoite:41


COPY editions/base/build.sh /tmp/build.sh
#COPY scripts/shared/build-shared.sh /tmp/build-shared.sh

COPY files/shared /

RUN mkdir -p /var/lib/alternatives && \
#    /tmp/build-shared.sh && \
    /tmp/build.sh && \
    echo "base" >> /usr/share/horizon/image_type && \
    ostree container commit
    #bootc container lint

