#!/usr/bin/env bash

image_type=$(cat /usr/share/horizon/image_type)

case "$image_type" in
    kinoite | kinoite_nvidia)
        konsoleprofile ColorScheme='Ashy Decay'
        plasma-apply-colorscheme AshyDecay
        plasma-apply-cursortheme Bibata-Modern-Ice
        plasma-apply-wallpaperimage /usr/share/horizon/wallpapers/space.png
        ;;
esac

systemctl --user disable horizon-theme-manager