ARG BASE_IMAGE=bazzite
FROM ghcr.io/ublue-os/${BASE_IMAGE}:stable

COPY ../files/shared /
COPY editions/cinnamon/build-cinnamon.sh /tmp/build-cinnamon.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build-cinnamon.sh && \
    ostree container commit && \
    bootc container lint
