FROM quay.io/fedora/fedora-bootc:41

COPY editions/asteroid/build.sh /tmp/build.sh


COPY files/asteroid /

RUN mkdir -p /var/lib/alternatives && \
#    /tmp/build-shared.sh && \
    /tmp/build.sh && \
    echo "asteroid" >> /usr/share/horizon/image_type && \
    ostree container commit
    #bootc container lint

