FROM ghcr.io/ublue-os/bazzite-nvidia-open:stable

COPY scripts/shared/build-shared.sh /tmp/build-shared.sh
COPY editions/aster/build.sh /tmp/build.sh

COPY files/shared /
COPY files/aster /

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build-shared.sh && \
    /tmp/build.sh && \
    echo "aster_nvidia" >> /usr/share/horizon/image_type && \
    ostree container commit
    #bootc container lint

