FROM ghcr.io/ublue-os/bazzite:stable

COPY editions/aster/build.sh /tmp/build.sh
COPY scripts/shared/build-shared.sh /tmp/build-shared.sh

COPY files/shared /

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build-shared.sh && \
    /tmp/build.sh && \
    echo "aster" >> /usr/share/horizon/image_type && \
    ostree container commit
    bootc container lint
